import AuthFooter from "../_components/authFooter"
import "../globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}<AuthFooter/></body>
    </html>
  )
}
